// A deck of cards has 52 cards
// Each card has a name, value, and suit
// The name of the card is a string (2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A)
// The value of the card is a number (2-11) - A is 11 or 1 - J, Q, K are 10
// The suit of the card is a string (♦, ♥, ♣, ♠)

export const deck = [
    { id: 1, name: "2", value: [2], suit: "♦", hidden: false },
    { id: 2, name: "3", value: [3], suit: "♦", hidden: false },
    { id: 3, name: "4", value: [4], suit: "♦", hidden: false },
    { id: 4, name: "5", value: [5], suit: "♦", hidden: false },
    { id: 5, name: "6", value: [6], suit: "♦", hidden: false },
    { id: 6, name: "7", value: [7], suit: "♦", hidden: false },
    { id: 7, name: "8", value: [8], suit: "♦", hidden: false },
    { id: 8, name: "9", value: [9], suit: "♦", hidden: false },
    { id: 9, name: "10", value: [10], suit: "♦", hidden: false },
    { id: 10, name: "J", value: [10], suit: "♦", hidden: false },
    { id: 11, name: "Q", value: [10], suit: "♦", hidden: false },
    { id: 12, name: "K", value: [10], suit: "♦", hidden: false },
    { id: 13, name: "A", value: [1, 11], suit: "♦", hidden: false },
    { id: 14, name: "2", value: [2], suit: "♥", hidden: false },
    { id: 15, name: "3", value: [3], suit: "♥", hidden: false },
    { id: 16, name: "4", value: [4], suit: "♥", hidden: false },
    { id: 17, name: "5", value: [5], suit: "♥", hidden: false },
    { id: 18, name: "6", value: [6], suit: "♥", hidden: false },
    { id: 19, name: "7", value: [7], suit: "♥", hidden: false },
    { id: 20, name: "8", value: [8], suit: "♥", hidden: false },
    { id: 21, name: "9", value: [9], suit: "♥", hidden: false },
    { id: 22, name: "10", value: [10], suit: "♥", hidden: false },
    { id: 23, name: "J", value: [10], suit: "♥", hidden: false },
    { id: 24, name: "Q", value: [10], suit: "♥", hidden: false },
    { id: 25, name: "K", value: [10], suit: "♥", hidden: false },
    { id: 26, name: "A", value: [1, 11], suit: "♥", hidden: false },
    { id: 27, name: "2", value: [2], suit: "♣", hidden: false },
    { id: 28, name: "3", value: [3], suit: "♣", hidden: false },
    { id: 29, name: "4", value: [4], suit: "♣", hidden: false },
    { id: 30, name: "5", value: [5], suit: "♣", hidden: false },
    { id: 31, name: "6", value: [6], suit: "♣", hidden: false },
    { id: 32, name: "7", value: [7], suit: "♣", hidden: false },
    { id: 33, name: "8", value: [8], suit: "♣", hidden: false },
    { id: 34, name: "9", value: [9], suit: "♣", hidden: false },
    { id: 35, name: "10", value: [10], suit: "♣", hidden: false },
    { id: 36, name: "J", value: [10], suit: "♣", hidden: false },
    { id: 37, name: "Q", value: [10], suit: "♣", hidden: false },
    { id: 38, name: "K", value: [10], suit: "♣", hidden: false },
    { id: 39, name: "A", value: [1, 11], suit: "♣", hidden: false },
    { id: 40, name: "2", value: [2], suit: "♠", hidden: false },
    { id: 41, name: "3", value: [3], suit: "♠", hidden: false },
    { id: 42, name: "4", value: [4], suit: "♠", hidden: false },
    { id: 43, name: "5", value: [5], suit: "♠", hidden: false },
    { id: 44, name: "6", value: [6], suit: "♠", hidden: false },
    { id: 45, name: "7", value: [7], suit: "♠", hidden: false },
    { id: 46, name: "8", value: [8], suit: "♠", hidden: false },
    { id: 47, name: "9", value: [9], suit: "♠", hidden: false },
    { id: 48, name: "10", value: [10], suit: "♠", hidden: false },
    { id: 49, name: "J", value: [10], suit: "♠", hidden: false },
    { id: 50, name: "Q", value: [10], suit: "♠", hidden: false },
    { id: 51, name: "K", value: [10], suit: "♠", hidden: false },
    { id: 52, name: "A", value: [1, 11], suit: "♠", hidden: false },
];
